spring:
  profiles:
    active: local # 기본 환경 선택

naver:
  client:
    clientId: QHgYiiIqE6yUEYuRkG3y
    clientSecret: f6seh0Mbgm
    accessTokenUri: https://nid.naver.com/oauth2.0/token
    userAuthorizationUri: https://nid.naver.com/oauth2.0/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://openapi.naver.com/v1/nid/me
google :
  client :
    clientId : 662583019632-e4gc1k6tk30ve1luvnq1lt5d2ugk96ea.apps.googleusercontent.com
    clientSecret: GAYJ7tqPldz3jgJppKTXJAol
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      

# local 환경
---
spring:
  profiles: local
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      
logging:
  level:
    org.springframework.security: DEBUG
    org:
      hibernate:
        type: trace